Update AlayaCare Cloud Tech Radar.csv
AlayaCare/alayacare-cloud-radar pull request #6
Opened 2021-05-13 19:17 UTC by estheban

Please, describe your changes in a few lines.  
Thanks for contributing!

# Description

[your description here]

2021-05-13 19:29 UTC, T0RAT0RA requested changes

2021-05-13 19:29 UTC, T0RAT0RA commented on AlayaCare Cloud Tech Radar.csv
> +"Adopt","Snowflake","Platforms","<p></p>"
You're missing the `isNew` column, let set it to FALSE for now.
Also add a link to the platform website when available.

```suggestion
"Adopt","Snowflake","Platforms","FALSE","<p><a href='https://www.snowflake.com/'>snowflake.com</a></p>"
```

2021-05-14 14:10 UTC, estheban commented on AlayaCare Cloud Tech Radar.csv
> +"Adopt","Looker","Platforms","<p></p>"
```suggestion
"Adopt","Looker","Platforms","TRUE","<p><a href='https://www.looker.com/'>looker.com</a></p>"
```

2021-05-14 14:11 UTC, estheban commented on AlayaCare Cloud Tech Radar.csv
> +"Adopt","DBT","languages-and-frameworks","<p></p>"
```suggestion
"Adopt","DBT","languages-and-frameworks","TRUE","<p><a href='https://www.getdbt.com/>getdbt.com</a></p>"
```

2021-05-17 12:59 UTC, closed without merging